services:
  postgres:
    image: postgres:17
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: vivamed
      POSTGRES_PASSWORD: vivamed@2024
      POSTGRES_DB: vivamed
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
